"""
Django settings for archiveooo project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import logging
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


import subprocess
MY_DOMAIN_NAME = subprocess.check_output('hostname --fqdn',
        shell=True, universal_newlines=True).strip()
MY_IP4 = subprocess.check_output('dig -4 +short @8.8.8.8 "$(hostname --fqdn)"',
        shell=True, universal_newlines=True).strip()


# Optionally, upload public files and docker images to s3
S3_BUCKET = None

AWS_PROFILE = None
# and/or:
AWS_ACCESS_KEY_ID = None
AWS_SECRET_ACCESS_KEY = None


# Optionally, protect some POSTs
RECAPTCHA_SITE_KEY=None
RECAPTCHA_SECRET_KEY=None


# Optionally (+ username, password)
DOCKERHUB_REPO = None



# Settings can be kept outside git...
logger = logging.getLogger("OOO")
try:
    from .local_settings_outside_git import *
except ImportError:
    logger.warning("I couldn't import local_settings_outside_git, will take settings from environment variables like $DJANGO_SECRET_KEY")


# ... and some can also come from the environment
# TODO: switch to django-environ?
if os.getenv('DJANGO_SECRET_KEY') is not None:
    SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if os.getenv('DJANGO_DEBUG') is not None:
    DEBUG = bool(os.getenv('DJANGO_DEBUG'))
if os.getenv('DJANGO_ADMINS') is not None:
    ADMINS = os.getenv('DJANGO_ADMINS').split()


# Including a DATABASE_URL
if not "DATABASES" in vars():
    import dj_database_url
    DATABASES = {}
    DATABASES['default'] = dj_database_url.config(conn_max_age=600,
            default="sqlite:///" + BASE_DIR + '/db.sqlite3')






LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


DEFAULT_FROM_EMAIL = "archive@archive.ooo"


PUBLIC_FILES_ROOT = BASE_DIR + '/public_files/'
PUBLIC_FILES_URL = '/public_files/'
IMAGES_DOWNLOAD_ROOT = BASE_DIR + '/dockerimg/'   # docker save
IMAGES_DOWNLOAD_URL = '/dockerimg/'
if os.getenv("DJANGO_S3_BUCKET"):
    S3_BUCKET = os.getenv("DJANGO_S3_BUCKET")



ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'ctfoood.apps.CtfooodConfig',
    'django.contrib.humanize',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'archiveooo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'archiveooo.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
#    {
#        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#    },
#    {
#        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#    },
#    {
#        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#    },
#    {
#        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Leaving it as UTC by default (note: should also set $TZ for subprocesses)
TIME_ZONE = 'UTC'

# gettext() translation -- disabled for now
USE_I18N = False

# Input/output of dates, numbers, etc. -- disabled for now
USE_L10N = False

# Store UTC, convert as needed
# TODO: Do I need mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql  ?
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
